global:
    depth_cut: 24.5
    res: 0.01
    pad: 0.1
    res_bo: 0.003
    flat_project: CAR
    mask_type: sirius
    band: i
    mask_thr: 0.5
    sys_collapse_type: average

ReduceCat:
    min_snr: 10.
    depth_method: fluxerr

SystMapper:
    ccd_drop: [9]

COSMOSWeight:
    n_neighbors: 20

CatMapper:
    pz_code: ephor_ab
    pz_mark: best
    pz_bins: [0.15,0.50,0.75,1.00,1.50]
    nz_bin_num: 100
    nz_bin_max: 4.0

PowerSpecter:
    ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
    gaus_covar_type: analytic
#    gaus_covar_type: gaus_sim
    noise_bias_type: analytic
#    noise_bias_type: pois_sim
    guess_spectrum: /global/homes/d/damonge/LSST/LSS_HSC/HyperSupremeStructure-HSC-LSS/hsc_lss_params/cls_guess_i24p5.txt
#    guess_spectrum: NONE
    mask_systematics: False
#    mask_systematics: True
    oc_dpj_list: [airmass,seeing,sigma_sky]
#    oc_dpj_list: [airmass,ccdtemp,ellipt,exptime,nvisit,seeing,sigma_sky,skylevel]
    oc_all_bands: True
#    oc_all_bands: False
    output_run_dir: CovAna_NoiAna_MskSirius_ClFit_Dpj0_DpjBands1
